default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: <%= ENV['db_name'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: <%= ENV['db_test_name'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['db_prod_name'] %>
